### ISSUE TITLE
是否添加新的功能呢？

### ISSUE THREAD

**Issue by cm-mimi** [dada909090/dada909090.github.io#2]
嗨dada878，我是小振！

我最近正常经常编写rawtext的文本显示，
正在寻找一个rawtext文本生成器的工具，
我特别感受编写代码很枯燥。觉得会花很多时间和精力。

如果能在rawtext生成器添加translate功能进去，
我会发现节省很多时间在rawtext的json编写上。像之前因为选择器上，
我只需要在你的网页输入选择器筛选条件，而不是还需要填入rawtext的语法和字符，
如果像手写rawtext，报错时我还需要花点精力和时间排查。
如果能添加我会很高兴！

具体的小要求：
{ "rawtext" : [ { "translate" : "%%2" , "with" : { "rawtext" : [ {"selector" : "@s[scores={point=1}]"} , { "text" : "1" } , { "text" : "0" }  ] } } ] }
当分数point是1时就输出他前面的text里的1，
如果不是就会执行后面的text里的0。
这种进阶的显示方法。

参考：https://www.bilibili.com/video/BV1SW4y1K7qe/?share_source=copy_web&vd_source=2d2f623076f219766e0e3c936b6be35c

是否可以接受呢？

**Comment by dada878** [comment]
小振你好，感謝你對這個專案的支持！
我近期正好打算要把這個東西重寫一次
並添加更多功能以及翻新 UI 介面
到時候會一併把你提出的功能加入
謝謝你提供建議！

沒想到還有人在用這個東西好感動 ><

**Comment by dada878** [comment]
所有的新功能已更新至 https://github.com/dada878/mcbe-command-generator ！

**Comment by cm-mimi** [comment]
太感谢了！：3
